### ISSUE TITLE
Determine what to do on IBC channel closure

### ISSUE THREAD

**Issue by shanev** [public-awesome/ics721#10]
Probably nothing.

**Comment by ezekiiel** [comment]
On `ChanCloseInit` it seems like we can safely error. We should test this to verify, but my understanding is that this will cancel the action.

`ChanCloseConfirm` is a different story though.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/30676292/180595565-363bef1d-4ef1-4b48-8dd4-bc67db0da877.png">

By the time we're receiving that message, our partner module has closed its connection. At that point, maybe we should delegate the ability to an admin (likely a community pool) to release all the tokens in escrow for that chain. The admin would only be able to do this if the channel had closed, locking those NFTs.

**Comment by ezekiiel** [comment]
From the [spec](https://github.com/cosmos/ibc/tree/master/spec/core/ics-004-channel-and-packet-semantics#closing-handshake):

> Once closed, channels cannot be reopened and identifiers cannot be reused.

This means that any NFTs that have IBCd away on that channel will never be recoverable.
