### ISSUE TITLE
Governance Sudo Methods?

### ISSUE THREAD

**Issue by JakeHartnell** [public-awesome/ics721#25]
Context: https://github.com/public-awesome/ics721/pull/22#discussion_r928139505

@jhernandezb wrote:
> should we have a governance sudo method that can restore closed channels ? This will happen more than you think currently for ics20 a proposal is submitted on chain to replace a closed channel for a valid one.

> Reason: Channel trust period very low and failing to update light client states during this period can lead to clients to be expired.

> Edit: nvm I think this is at the light client level but should be tested

We may want some governance `sudo` methods for such things as restoring closed channels or performing certain admin functions for managing this contract. Though perhaps, current Cosmos SDK governance around IBC is good enough.

This issue is to make sure we have a discussion around this, and at the very least test edge cases like closed channels.

**Comment by 0xekez** [comment]
testing for polytone [confirms that](https://github.com/0xekez/cw-ibc-example/blob/main/tests/strangelove/light_client_expiry_test.go) light client expiry / missbehavior doesn't need special handling by protocols.
