### ISSUE TITLE
Ibc3 feature failing tests

### ISSUE THREAD

**Issue by Art3miX** [public-awesome/ics721#36]
![image](https://user-images.githubusercontent.com/40179351/202894484-737566e0-a666-4365-8973-69b2697373af.png)
 In the ibc3 feature, the new method now accepts 2 arguments, with the relayer addr as the 2nd.

Not sure what it means yet, but I think its need to be looked into.

**Comment by 0xekez** [comment]
https://github.com/CosmWasm/cosmwasm/pull/1302

**Comment by Art3miX** [comment]
https://github.com/CosmWasm/cosmwasm/pull/1302#discussion_r871074572

> But yeah, we'll probably remove all non-v3 code soon anyways.

maybe 6 months is not soon enough, or something changed, either way, seems to be the best bet is to use ibc3.

**Comment by 0xekez** [comment]
fixed by: https://github.com/public-awesome/ics721/commit/1b086c6934ffe8667e89db3632501d48d795b2f4
