### ISSUE TITLE
Entry Incentives and Exit Taxes

### ISSUE THREAD

**Issue by 0xekez** [public-awesome/ics721#52]
We'd like to be able to incentivize NFT's entering Stargaze, and require a tax for NFTs exiting Stargaze.

## Entry Inventives

![image](https://user-images.githubusercontent.com/30676292/233726806-fa9201f2-35f1-40fb-b40b-ec094ebf512c.png)

1. A subDAO controls what collections should be incentivized.
2. If a NFT from an incentivized collections enters Stargaze, an entry incentives contract sends funds to the NFT receiver.

## Exit Incentives

![image](https://user-images.githubusercontent.com/30676292/233727048-30f4ba52-165b-4806-a615-2a13b6a02148.png)

First, funds are deposited with the exit tax module. Then, the NFT is transferred via the exit contract which serves [as a proxy](https://github.com/0xekez/cw721-proxy) for the ICS-721 contract. The module being a proxy means that it is the only module allowed to perform NFT transfers, thus making the exit tax required. The two messages needed can be abstracted by a frontend which sends both messages in one transaction.

In this flowchart, the exit tax is paid even if the NFT transfer fails (ACK-FAIL, or timeout is returned). We could easily extend this so that the exit proxy receives a transfer completion callback (which we'll add as part of [integrating](https://github.com/DA0-DA0/polytone/wiki/How-Polytone-Supports-Outposts) with outposts), and thus allow refunding the exit tax if the transfer fails.

## Safety

In order for this system to be safe:

1. The exit tax must be larger than the entry inventive to prevent looping.
2. The entry tax must be limited to an allow-list of NFT collections, as otherwise a permissionless chain could instantiate and transfer infinite NFTs to drain the entry incentives.

**Comment by 0xekez** [comment]
@shanev - I think the outstanding question here is what to do with the exit tax funds. I figure we could either burn them, transfer to an address, or use them to fund entry inventives.

**Comment by 0xekez** [comment]
Another important point while implementing this is to take care of how the entry-incentives module panics. If the ICS-721 `on_entry` hook panics, the NFT being transferred will be stuck until a timeout occurs. We need to design:

1. How does the entry-inventives module handle being out of funds?
2. Are there any inputs that could cause it to panic?
3. If an unexpected panic occurs, what should we do?

**Comment by shanev** [comment]
> 

I think exit tax funds can be just sent to an address which could be a burn address, a DAO, or whatever. It would be great to support community pools as well, but I don't think it's worth supporting something that will end up being legacy soon (since they will get module accounts eventually).

**Comment by shanev** [comment]
> 1. How does the entry-inventives module handle being out of funds?
Can it check its balance before the transfer and throw an error?

> 2. Are there any inputs that could cause it to panic?
> 3. If an unexpected panic occurs, what should we do?
I say try to undo the transfer on any kind of panic.

**Comment by shanev** [comment]
> @shanev - I think the outstanding question here is what to do with the exit tax funds. I figure we could either burn them, transfer to an address, or use them to fund entry inventives.

I think exit tax funds can be just sent to an address which could be a burn address, a DAO, or whatever. It would be great to support community pools as well, but I don't think it's worth supporting something that will end up being legacy soon (since they will get module accounts eventually).

**Comment by 0xekez** [comment]
> I say try to undo the transfer on any kind of panic.

To do this, we'll need two things:

1. The `on_entry` hook should be dispatched as `SubMsg::reply_on_error` with a [gas limit](https://github.com/DA0-DA0/polytone/blob/main/contracts/voice/src/ibc.rs#L26-L33). If an error occurs during the callback, an ACK-FAIL should be returned instantly, thus failing the transfer.
2. The hook receiver should be able to remove itself. In practice, this means that the entry incentives module should have a message that its manager can execute which removes it from the ICS-721 contract. This lets us "turn off" entry incentives if needed.

**Comment by humanalgorithm** [comment]
This is currently being solved in Ark's new proxy repo, example of check paid is here: 
https://github.com/arkprotocol/ics721-plus/blob/main/packages/cw-ics721-outgoing-proxy/src/lib.rs#L140
repo here: https://github.com/arkprotocol/ics721-plus/
